### ISSUE TITLE
Actividad 2, Infografía, Edgar Fabián Castro Pérez 

### ISSUE THREAD

**Issue by 11042002** [SistemasTecTlaxiaco/actividad-2-infografia-11042002#1]
[Actividad 2, Infografía, Edgar Fabian Castro Pérez.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-infografia-11042002/files/9463852/ACTIVIDAD.2.pdf)

**Comment by Jaczibeth** [comment]
de 20% sacaste 19%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
